"""Workspace management commands."""

from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from ...core.exceptions import InvalidMissionIDError
from ...core.workspace import Workspace
from ..utils.validation import validate_mission_id

app = typer.Typer(help="Workspace management commands")
console = Console()


@app.command("init")
def init_workspace(
    mission_id: str = typer.Argument(..., help="Mission ID (e.g., MF-001)"),
    force: bool = typer.Option(False, "--force", help="Overwrite existing mission"),
) -> None:
    """Initialize a new mission workspace."""

    # Validate mission ID
    if not validate_mission_id(mission_id):
        raise InvalidMissionIDError(mission_id)

    # Create workspace if it doesn't exist
    try:
        workspace = Workspace()
    except Exception:
        # Workspace doesn't exist, create it
        workspace_root = Path.cwd()
        workspace_dir = workspace_root / ".missionforge"
        workspace_dir.mkdir(exist_ok=True)
        workspace = Workspace(start_path=workspace_root)

    mission_path = workspace.mission_path(mission_id)

    if mission_path.exists() and not force:
        console.print(f"[yellow]Mission {mission_id} already exists[/yellow]")
        console.print("Use --force to overwrite")
        raise typer.Exit(1)

    # Create directory structure
    mission_path.mkdir(parents=True, exist_ok=True)
    (mission_path / "sub-missions").mkdir(exist_ok=True)

    # Create template files
    _create_mission_template(mission_path / "mission.yaml", mission_id)
    _create_plan_template(mission_path / "plan.yaml")
    (mission_path / "report.md").touch()

    console.print(f"[green]✓[/green] Initialized mission {mission_id}")
    console.print(f"\n[bold]Next steps:[/bold]")
    console.print(f"1. Edit {mission_path / 'mission.yaml'}")
    console.print(f"2. Run: missionforge mission validate {mission_id}")


@app.command("status")
def workspace_status() -> None:
    """Show workspace status and missions."""

    try:
        workspace = Workspace()
    except Exception:
        console.print("[yellow]No workspace initialized[/yellow]")
        console.print("Run: missionforge workspace init <mission-id>")
        raise typer.Exit(1)

    if not workspace.exists():
        console.print("[yellow]No workspace initialized[/yellow]")
        console.print("Run: missionforge workspace init <mission-id>")
        raise typer.Exit(1)

    # List missions
    missions = workspace.list_missions()

    if not missions:
        console.print("[yellow]No missions found[/yellow]")
        console.print(f"\nWorkspace location: {workspace.workspace_dir}")
        return

    table = Table(title="Missions")
    table.add_column("Mission ID", style="cyan")
    table.add_column("Status", style="green")
    table.add_column("Sub-missions", justify="right")

    for mission_id in missions:
        mission_path = workspace.mission_path(mission_id)
        sub_missions_dir = mission_path / "sub-missions"
        sub_mission_count = 0
        if sub_missions_dir.exists():
            sub_mission_count = len(list(sub_missions_dir.glob("*.yaml")))
        table.add_row(mission_id, "Active", str(sub_mission_count))

    console.print(table)
    console.print(f"\nWorkspace location: {workspace.workspace_dir}")


def _create_mission_template(path: Path, mission_id: str) -> None:
    """Create mission.yaml template.

    Args:
        path: Path where template should be created.
        mission_id: Mission identifier.
    """
    template = f"""# Mission: {mission_id}
id: {mission_id}
goal: |
  Describe the high-level goal of this mission.
  What should be accomplished?

# Paths that sub-missions cannot modify
forbidden_paths:
  - "core/**"
  - "config/**"

# Aggregate metrics to validate across all sub-missions
aggregate_metrics:
  total_files_changed:
    max: 50
  total_lines_changed:
    max: 1000

# Test command to validate mission completion
test_command: "pytest tests/"

# Sub-missions will be listed here after decomposition
sub_missions: []
"""
    path.write_text(template)


def _create_plan_template(path: Path) -> None:
    """Create plan.yaml template.

    Args:
        path: Path where template should be created.
    """
    template = """# Execution plan (generated by 'missionforge plan')
execution_order: []
dependency_graph: {}
"""
    path.write_text(template)

# Made with Bob
